### ISSUE TITLE
Issue with hive-site.xml variables in group_vars

### ISSUE THREAD

**Issue by gonzaloetjo** [TOSIT-IO/tdp-getting-started#128]
Currently there's no `inventory/group_vars/hive_ms.yml` file. Despite this, the `hive-site.xml` configuration inherits `inventory/group_vars/hive_s2.yml` properties  in master-03 (checked by adding properties that didn't exist in hive.yml).

I've tested the other-way around (declaring new properties in the `ms` instead of `s2`) and found:

- `Hive-site.xml` properties set in hive_ms.yml  and not in hive_s2.yml are inherited by server2 hive-site.xml ONLY in master-03.
- In master-02, the server2 conf doesn't inherit those properties. 
- This might be so because hive server2 and metastore configurations coexist in the same folder in master-03, while in master-02 only server2 is installed.

**Comment by leopaul36** [comment]
@mehdibn  could this be solved by https://github.com/TOSIT-IO/tdp-collection/pull/295 ?

**Comment by gboutry** [comment]
As far as I can see [here](https://github.com/TOSIT-IO/tdp-collection-extras/blob/b9e6eff20d3cd87c59e0eaccd03d1ac13fcd5d61/roles/ansible-tdp-common-actions/templates/ansible-hosts.j2), Hiveserver 2 is deployed on master-02 and master-03, while the metastore is only deployed on master-03. This explains why you see this behavior only on master-03 where you have the 2 ansible groups `hive_s2` and `hive_ms` colliding.

The `resolve` plugin will apply merge all tdp_vars, and then apply on top of it the `group_vars`. The `group_vars` are "resolved" by Ansible, and since master-03 has both the `hive_s2` and `hive_ms` groups, it merges them together (because of the `hash_behaviour=merge`).

2 solutions:
- Setup tdp_vars in tdp-getting-started, and have the configuration written in the tdp_vars (but you would need to follow the updates on default variables from the different collections)
- Remove `hive_s2` from master-03 (but if you want multiple hs2 it's not a viable solution)

**Comment by rpignolet** [comment]
I think the current refactor of getting started will solve it, `tdp_vars` are copied from `tdp_vars_defaults`.

**Comment by rpignolet** [comment]
Following #196, you should configure Hive with `tdp_vars` and not use `group_vars` to do it.
