### ISSUE TITLE
Error in the deploy-service-start-on-boot-policies ansible playbook

### ISSUE THREAD

**Issue by Erzangel** [TOSIT-IO/tdp-getting-started#145]
## How the issue occured

While deploying `tdp-getting-started` using the `ansible-playbook deploy-all.yml` command, an error occurs in a task within `deploy-service-start-on-boot-policies.yml`:

```
TASK [Apply livy-server service start on boot policy] ************************
failed: [localhost -> edge-01(192.168.56.16)] (item=edge-01) => changed=false 
  ansible_loop_var: item
  item: edge-01
  msg: 'Could not find the requested service livy-server-spark2: host'
```

Other tasks performing similar actions seem to work fine. Not being used to Hadoop, I do not know how to get further logs if this error is not reproducible.

## Configuration

I am on NixOS, have all dependencies installed, and followed steps in the `Quick Start` section of the README.
`setup.sh` was given the `stable` option. Currently testing if using `latest` produces the same result.

Thank you in advance for looking into this!

EDIT: I can confirm that using `./scripts/setup.sh -r latest` does not fix the problem.

**Comment by mehdibn** [comment]
@Erzangel thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.

Discussions are in progress in order to review this issue. We will reach out to you as soon as possible.
Please note that Livy is part of tdp-extras : we don't ganratee a full integration in TDP.

Thank you again for your contribution to TDP.
