### ISSUE TITLE
Issue with tez

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-getting-started#217]
Hello,

After installing hive, i tried to launch tests as mentionned in your README, but when i tried to lanch
"INSERT INTO TABLE table1 VALUES (1, 'one'), (2, 'two');"

it stays stuck with this message "INFO  : Tez session hasn't been created yet. Opening session"

From hive server logs: INFO [HiveServer2-HttpHandler-Pool: Thread-5268] thrift.ThriftHttpServlet: Failed to authenticate with http/_HOST kerberos principal, trying with hive/_HOST kerberos principal
All the tickets kerberos are working properly.

What do you think it could be related to?

Thank you in advance,

Best Regards,

**Comment by leopaul36** [comment]
Hello @YasmineZamni, I don't think the error you put is relevant because I have the same kind of log on my side, plus it's a INFO not an ERROR.

My guess is that your Tez containers are not being launched in YARN.

Can you see an application_id belonging to tdp_user in the YARN UI? Make sure your YARN NM nodes are active and that the UI is reporting Memory and Cores ready to be used.

**Comment by YasmineZamni** [comment]
Hello @leopaul36,

Yes i see the application id from yarn ui and from the yarn rm but it but it remains stuck in accepted status.

I checked all service are up.

Attached is a capture of yarn ui.

Regards,

![Uploading image.png…]()

**Comment by YasmineZamni** [comment]
Hello,

It was a problem of rights in the disks.

Best Regards,

**Comment by leopaul36** [comment]
Thanks for the input @YasmineZamni 

Closing as resolved
